spring:
  application:
    name: alibaba-sentinel-datasource-nacos
  cloud:
    sentinel:
      transport:
        dashboard: ${sentinel.host}:8849  #sentinel dashboard的访问地址，根据上面准备工作中启动的实例配置
      #eager: true
      datasource:
        ds:
          nacos:
            server-addr: ${nacos.url}:8001  #nacos的访问地址，启动的实例配置
            groupId: DEFAULT_GROUP  #nacos中存储规则的groupId
            dataId: ${spring.application.name}-sentinel #nacos中存储规则的dataId
            rule-type: flow   #该参数是spring cloud alibaba升级到0.2.2之后增加的配置，用来定义存储的规则类型。所有的规则类型可查看枚举类：org.springframework.cloud.alibaba.sentinel.datasource.RuleType，每种规则的定义格式可以通过各枚举值中定义的规则对象来查看，比如限流规则可查看：com.alibaba.csp.sentinel.slots.block.flow.FlowRule


